name: CI-CD

on:
    push:
        branches:
            - main            

jobs:
    test:
        name: Running unit tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 20.11.1
              uses: actions/setup-node@v4
              with:
                node-version: '20.11.1'

            - name: Install dependencies
              run: |
                  cd calculator                                 
                  npm i

            - name: Run unit tests
              run: |
                  cd calculator
                  npm test

    build:
      name: Build
      runs-on: ubuntu-latest
      needs: test
      steps:
          - uses: actions/checkout@v4
          - name: Use Node.js 20.11.1
            uses: actions/setup-node@v4
            with:
              node-version: '20.11.1'

          - name: Install dependencies
            run: |
                cd calculator                                   
                npm i
                
          - name: Run build
            run: |
                cd calculator                                 
                npm run build

    report:
        name: Generate and Upload Test Report
        runs-on: ubuntu-latest
        needs: test
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 20.11.1
              uses: actions/setup-node@v4
              with:
                node-version: '20.11.1'

            - name: Install dependencies
              run: |
                  cd calculator                                 
                  npm i

            - name: Generate Test Report
              run: |
                  cd calculator
                  npx jest --coverage
              env:
                CI: true

            - name: Upload Test Report
              uses: actions/upload-artifact@v4
              with:
                name: test-report
                path: calculator/coverage/lcov-report/index.html

            - name: Deploy to GitHub Pages
              if: success()
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./coverage/lcov-report
